Project-MONAI/monai-deploy-informatics-gateway

docs/setup/setup.md, src/Api/MessageBroker/Message.cs, src/Api/MessageBroker/WorkflowRequestMessage.cs, src/Api/Storage/BlockStorageInfo.cs, src/Api/Storage/DicomFileStorageInfo.cs, src/Api/Storage/FhirFileStorageInfo.cs, src/Api/Storage/FileStorageInfo.cs, src/Api/Storage/Payload.cs, src/Configuration/DicomConfiguration.cs, src/Configuration/DicomJsonOptions.cs, src/Database/Migrations/20220203222116_R1_Initialize.Designer.cs, src/Database/Migrations/20220203222116_R1_Initialize.cs, src/Database/Migrations/InformaticsGatewayContextModelSnapshot.cs, src/Database/PayloadConfiguration.cs, src/InformaticsGateway/Common/DicomToJsonConverter.cs, src/InformaticsGateway/Common/DicomToolkit.cs, src/InformaticsGateway/Program.cs, src/InformaticsGateway/Services/Connectors/DataRetrievalService.cs, src/InformaticsGateway/Services/Connectors/PayloadAssembler.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityHandler.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityManager.cs, src/InformaticsGateway/Services/Storage/SpaceReclaimerService.cs, src/InformaticsGateway/Test/Common/DicomToolkitTest.cs, src/InformaticsGateway/Test/Services/Connectors/DataRetrievalServiceTest.cs, src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs, src/InformaticsGateway/Test/Services/Scp/ApplicationEntityManagerTest.cs, src/InformaticsGateway/Test/Services/Storage/SpaceReclaimerServiceTest.cs
Fixes #36
- convert and store DICOM to JSON format.
- An enhancement has been filed with [fo-dicom](https://github.com/fo-dicom/fo-dicom/issues/1321) to support the option of not writing `other` value types.  Until then, a copy of the code is included.
- update WorkflowRequestMessage structure
**Ready**
=> Extract and store DICOM JSON.

.github/workflows/ci.yml
Enable SonarCloud for code scanning
**Ready**
=> Enable SonarCloud

.github/workflows/ci.yml
The version calculated within the `build` job using MSBuild is different from the `calc-version` job and results in naming and referencing build artifacts with the wrong name.
**Ready**
=> Fix CI pipeline to use version number from calc-version job

src/Configuration/DataExportConfiguration.cs, src/Configuration/DicomConfiguration.cs, src/Configuration/DicomWebConfiguration.cs, src/Configuration/FhirConfiguration.cs, src/Configuration/InformaticsGatewayConfiguration.cs, src/Configuration/MessageBrokerConfiguration.cs, src/Configuration/MessageBrokerConfigurationKeys.cs, src/Configuration/RetryConfiguration.cs, src/Configuration/ScpConfiguration.cs, src/Configuration/ScuConfiguration.cs, src/Configuration/StorageConfiguration.cs
Fix typos in `ConfigurationKeyName` and use `ConfigurationKeyName` instead of `JsonProperty` for `IOptions` (de)serialization.
**Ready**
=> Fix typos in ConfigurationKeyName

docs/setup/schema.md, src/.sonarlint/Monai.Deploy.InformaticsGateway.slconfig, src/.sonarlint/project-monai_monai-deploy-informatics-gateway/CSharp/SonarLint.xml, src/.sonarlint/project-monai_monai-deploy-informatics-gatewaycsharp.ruleset, src/.sonarlint/sonar.settings.json, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Api/Test/Monai.Deploy.InformaticsGateway.Api.Test.csproj, src/CLI/Monai.Deploy.InformaticsGateway.CLI.csproj, src/CLI/Test/Monai.Deploy.InformaticsGateway.CLI.Test.csproj, src/Common/Monai.Deploy.InformaticsGateway.Common.csproj, src/Common/Test/Monai.Deploy.InformaticsGateway.Common.Test.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/Configuration/Test/Monai.Deploy.InformaticsGateway.Configuration.Test.csproj, src/Database/Monai.Deploy.InformaticsGateway.Database.csproj, src/DicomWebClient/CLI/Monai.Deploy.InformaticsGateway.DicomWeb.Client.CLI.csproj, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, src/InformaticsGateway/Test/DummyMessagingService.cs, src/InformaticsGateway/Test/Monai.Deploy.InformaticsGateway.Test.csproj, src/InformaticsGateway/Test/Services/Export/DicomWebExportServiceTest.cs, src/InformaticsGateway/Test/Services/Export/ExportServiceBaseTest.cs, src/InformaticsGateway/Test/Services/Export/ScuExportServiceTest.cs, src/InformaticsGateway/appsettings.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj, tests/Integration.Test/configs/informatics-gateway.json
- Re-queue export request instead of reject when disk space is low.
- Subscribe with queue names
**Ready**
=> Queue logic updates

src/Configuration/DatabaseConfiguration.cs, src/Configuration/InformaticsGatewayConfiguration.cs, src/InformaticsGateway/Repositories/InferenceRequestRepository.cs, src/InformaticsGateway/Services/Connectors/DataRetrievalService.cs, src/InformaticsGateway/Services/Connectors/PayloadAssembler.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs, src/InformaticsGateway/Services/Storage/SpaceReclaimerService.cs, src/InformaticsGateway/Test/Repositories/InferenceRequestRepositoryTest.cs, src/InformaticsGateway/Test/Services/Connectors/DataRetrievalServiceTest.cs, src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs
Fixes #27.
Add new options to allow users to configure retries for any database connection errors.
Other Polly calls were already updated.
**Ready**
=> New options to configure database retries

Dockerfile
Upgrade base image to use `6.0-jammy` (ubuntu 22.04) based.
**Ready**
=> Switch base image to 6.0-jammy

doc/dependency_decisions.yml, docker-compose/docker-compose.dev.yml, docs/compliance/third-party-licenses.md, src/Common/Monai.Deploy.InformaticsGateway.Common.csproj, src/Configuration/DicomConfiguration.cs, src/DicomWebClient/CLI/Monai.Deploy.InformaticsGateway.DicomWeb.Client.CLI.csproj, src/DicomWebClient/Monai.Deploy.InformaticsGateway.DicomWeb.Client.csproj, src/InformaticsGateway/Common/DicomExtensions.cs, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Connectors/DataRetrievalService.cs, src/InformaticsGateway/Services/DicomWeb/IStreamsWriter.cs, src/InformaticsGateway/Services/Export/ScuExportService.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityHandler.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityManager.cs, src/InformaticsGateway/Services/Scp/IApplicationEntityHandler.cs, src/InformaticsGateway/Services/Scp/ScpServiceInternal.cs, src/InformaticsGateway/Test/Common/DicomFileStorageMetadataExtensionsTest.cs, src/InformaticsGateway/Test/Services/Scp/ApplicationEntityHandlerTest.cs, src/InformaticsGateway/Test/Shared/DicomScpFixture.cs, tests/Integration.Test/Drivers/DicomScp.cs, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj
- Upgrade fo-dicom to 5.0.3 and handle breaking changes in `DicomService` and `DicomClient`.
- New configuration to allow users to configure whether to auto-validate DICOM values on JSON serialization with default to false.
**Ready**
=> Update fo-dicom to 5.0.3

src/Api/Storage/Payload.cs, src/Api/Storage/StorageObjectMetadata.cs, src/Configuration/ConfigurationValidator.cs, src/Configuration/StorageConfiguration.cs, src/Configuration/TemporaryDataStorageLocation.cs, src/Configuration/Test/ConfigurationValidatorTest.cs, src/Database/PayloadConfiguration.cs, src/InformaticsGateway/Common/FileStorageMetadataExtensions.cs, src/InformaticsGateway/Logging/Log.700.PayloadService.cs, src/InformaticsGateway/Services/Connectors/DataRetrievalService.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationActionHandler.cs, src/InformaticsGateway/Services/DicomWeb/IStreamsWriter.cs, src/InformaticsGateway/Services/Fhir/FhirJsonReader.cs, src/InformaticsGateway/Services/Fhir/FhirService.cs, src/InformaticsGateway/Services/Fhir/FhirXmlReader.cs, src/InformaticsGateway/Services/HealthLevel7/MllpService.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityHandler.cs, src/InformaticsGateway/Test/Common/DicomFileStorageMetadataExtensionsTest.cs, src/InformaticsGateway/Test/Services/Connectors/DataRetrievalServiceTest.cs, src/InformaticsGateway/Test/Services/DicomWeb/StreamsWriterTest.cs, src/InformaticsGateway/Test/Services/Fhir/FhirJsonReaderTest.cs, src/InformaticsGateway/Test/Services/Fhir/FhirServiceTest.cs, src/InformaticsGateway/Test/Services/Fhir/FhirXmlReaderTest.cs, src/InformaticsGateway/Test/Services/HealthLevel7/MllpServiceTest.cs, src/InformaticsGateway/Test/Services/Scp/ApplicationEntityHandlerTest.cs, src/InformaticsGateway/Test/Services/Storage/ObjectUploadServiceTest.cs
Fixes #154
- Added new configurations (`tempStorageLocation`) to enable users to use either `Memory` or `Disk` (default) for storing incoming data.  
- For `disk` option:
- users must configure `bufferRootPath`.
- `bufferSize` allows users to set disk buffer size with a default value of 128KB
- For `Memory` option:
- `GC.Collect` is called upon a successful upload to force the garbage collector to compact the LOH
**Ready**
=> Ability to switch temporary storage to use either memory or disk

src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Program.cs, src/InformaticsGateway/appsettings.json
Added logging packages (serilog) and the work needed to log across the workflow
**Ready**
=> Nds adding logging

src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Program.cs, src/InformaticsGateway/appsettings.json
Reverting this for 0.3.1 release
=> Revert "Nds adding logging"

src/InformaticsGateway/Services/Storage/ObjectUploadService.cs, tests/Integration.Test/StepDefinitions/HealthLevel7Definitions.cs
Fixes #183 .
The data stream position needs to reset to the beginning before attempting to upload.
**Ready**
=> Reset stream position before upload

doc/dependency_decisions.yml, docs/compliance/third-party-licenses.md, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Connectors/PayloadNotificationActionHandler.cs, src/InformaticsGateway/appsettings.Development.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj
Fixes #184 
Update messaging library to fix issue connecting to RMQ after the connection is recvered.
**Ready**
=>  update messaging lib to fix RMQ connection issues

src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj
Signed-off-by: Neil South <neil.south@answerdigital.com>
Fixes 
Solution not building due to missing sierlog package
A few sentences describing the changes proposed in this pull request.
**Ready**
=> fix for missing nugets

src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/InformaticsGateway/Logging/Log.500.ExportService.cs, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Export/DicomWebExportService.cs, src/InformaticsGateway/Services/Export/ExportRequestDataMessage.cs, src/InformaticsGateway/Services/Export/ExportRequestEventDetails.cs, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, src/InformaticsGateway/Services/Export/ScuExportService.cs, src/InformaticsGateway/Test/Services/Export/DicomWebExportServiceTest.cs, src/InformaticsGateway/Test/Services/Export/ExportServiceBaseTest.cs, src/InformaticsGateway/Test/Services/Export/ScuExportServiceTest.cs, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj
Updates DICOMweb export & DIMSE export services to include export statuses for each file.
**Ready**
=> Include export status for every file

src/InformaticsGateway/Test/Services/Connectors/PayloadAssemblerTest.cs, src/InformaticsGateway/Test/Services/Connectors/PayloadMoveActionHandlerTest.cs, src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs, src/InformaticsGateway/Test/Services/Fhir/FhirServiceTest.cs, src/InformaticsGateway/Test/Services/Scu/ScuServiceTest.cs
Signed-off-by: Victor Chang <vicchang@nvidia.com>
=> Merge patch/0.3.2 into develop

src/InformaticsGateway/Program.cs, src/InformaticsGateway/nlog.config
Fixes #209 
Include all scope properties by default for Network logging
**Ready**
=> Include scope properties

.github/workflows/ci.yml, doc/dependency_decisions.yml, docs/compliance/third-party-licenses.md, src/CLI/Monai.Deploy.InformaticsGateway.CLI.csproj, src/InformaticsGateway/Services/Storage/ObjectUploadService.cs, src/InformaticsGateway/appsettings.Test.json, tests/Integration.Test/StepDefinitions/AcrApiStepDefinitions.cs, tests/Integration.Test/StepDefinitions/ExportServicesStepDefinitions.cs, tests/Integration.Test/StepDefinitions/FhirDefinitions.cs, tests/Integration.Test/StepDefinitions/HealthLevel7Definitions.cs, tests/Integration.Test/StepDefinitions/SharedDefinitions.cs, tests/Integration.Test/debug.sh
- Update licenses to reflect recent dependabot changes
- Fix skywalking-eye failure
- Use dotnet's built-in vulnerability scan for nuget packages
**Ready*
=> Update licenses & CI

doc/dependency_decisions.yml, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj
Signed-off-by: Neil South <neil.south@answerdigital.com>
Upped messaging version
=> upped messaging version

src/Configuration/Test/ValidationExtensionsTest.cs, src/Configuration/ValidationExtensions.cs
Update validation logic for AET, IP address and hostnames/domain names.
**Ready**
=> Improve validation for AET, IP & hostnames/domain names

src/Api/DicomAssociationInfo.cs, src/Database/Api/Repositories/IDicomAssociationInfoRepository.cs, src/Database/DatabaseManager.cs, src/Database/EntityFramework/Configuration/DicomAssociationInfoConfiguration.cs, src/Database/EntityFramework/InformaticsGatewayContext.cs, src/Database/EntityFramework/Migrations/20221123174502_R3_0.3.5.Designer.cs, src/Database/EntityFramework/Migrations/20221123174502_R3_0.3.5.cs, src/Database/EntityFramework/Repositories/DicomAssociationInfoRepository.cs, src/Database/EntityFramework/Test/DicomAssociationInfoRepositoryTest.cs, src/Database/EntityFramework/Test/SqliteDatabaseFixture.cs, src/Database/MongoDB/Configurations/DicomAssociationInfoConfiguration.cs, src/Database/MongoDB/Integration.Test/DicomAssociationInfoRepositoryTest.cs, src/Database/MongoDB/Integration.Test/MongoDatabaseFixture.cs, src/Database/MongoDB/MongoDatabaseMigrationManager.cs, src/Database/MongoDB/Repositories/DicomAssociationInfoRepository.cs, src/InformaticsGateway/Logging/Log.100.200.ScpService.cs, src/InformaticsGateway/Services/Scp/ScpServiceInternal.cs, src/InformaticsGateway/Test/Shared/DicomScpFixture.cs, tests/Integration.Test/Common/DicomScp.cs
Record DICOM association info in the database.
**Ready/Work in progress/Hold**
=> Record associations to the database

doc/dependency_decisions.yml, docs/compliance/third-party-licenses.md, src/Client/Test/packages.lock.json, src/Database/DatabaseManager.cs, src/Database/EntityFramework/Configuration/SR.cs, src/Database/Monai.Deploy.InformaticsGateway.Database.csproj, src/Database/packages.lock.json, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Http/Startup.cs, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/packages.lock.json
Fix to support both MongoDB & SQLite DB health checks.
**Ready**
=> Properly support database health checks based on configuration.

doc/dependency_decisions.yml, docs/changelog.md, docs/compliance/third-party-licenses.md, src/Client/Test/packages.lock.json, src/Database/DatabaseManager.cs, src/Database/packages.lock.json, src/InformaticsGateway/Services/Http/Startup.cs, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/packages.lock.json
The previous build 0.3.6 is DOA due to a merge error. 
This fixes the database health check registration logic.
**Ready**
=> Register database health check

src/InformaticsGateway/Services/Connectors/PayloadAssembler.cs, tests/Integration.Test/Common/Assertions.cs, tests/Integration.Test/Common/DataProvider.cs, tests/Integration.Test/Common/DicomCStoreDataClient.cs, tests/Integration.Test/Drivers/RabbitMqConsumer.cs, tests/Integration.Test/Features/AcrApi.feature, tests/Integration.Test/Features/DicomDimseScp.feature, tests/Integration.Test/StepDefinitions/AcrApiStepDefinitions.cs, tests/Integration.Test/StepDefinitions/DicomDimseScpServicesStepDefinitions.cs, tests/Integration.Test/StepDefinitions/DicomWebStowServiceStepDefinitions.cs, tests/Integration.Test/StepDefinitions/ExportServicesStepDefinitions.cs, tests/Integration.Test/StepDefinitions/FhirDefinitions.cs, tests/Integration.Test/StepDefinitions/HealthLevel7Definitions.cs, tests/Integration.Test/StepDefinitions/SharedDefinitions.cs
Fixes a regression where the payload assembler is not waiting for the timeout associated with the AE title.
**Ready**
=> Fix payload assembler not respecting user configured timeout window

src/Api/Storage/Payload.cs, src/Common/ExtensionMethods.cs, src/Configuration/DicomWebConfiguration.cs, src/Configuration/ScuConfiguration.cs, src/InformaticsGateway/Common/PostPayloadException.cs, src/InformaticsGateway/Logging/Log.3000.PayloadAssembler.cs, src/InformaticsGateway/Logging/Log.500.ExportService.cs, src/InformaticsGateway/Logging/Log.700.PayloadService.cs, src/InformaticsGateway/Services/Connectors/PayloadAssembler.cs, src/InformaticsGateway/Services/Connectors/PayloadMoveActionHandler.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationActionHandler.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs, src/InformaticsGateway/Services/Export/DicomWebExportService.cs, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, src/InformaticsGateway/Services/Export/ScuExportService.cs, src/InformaticsGateway/Test/Services/Export/DicomWebExportServiceTest.cs, src/InformaticsGateway/Test/Services/Export/ExportServiceBaseTest.cs, src/InformaticsGateway/Test/Services/Export/ScuExportServiceTest.cs
Checks and resets ActionBlock<> queues used for moving and publishing payloads if unable to post any messages to them.
**Ready**
=> Resets ActionBlock if faulted or cancelled.

src/InformaticsGateway/Services/Http/DestinationAeTitleController.cs, src/InformaticsGateway/Services/Scu/ScuService.cs, src/InformaticsGateway/Services/Scu/ScuWorkRequest.cs, src/InformaticsGateway/Test/Services/Scu/ScuServiceTest.cs
Currently, echo requests are blocking the `ScuService` thread allowing for only one request to be processed at a time. Long running requests (such as the ones failing to reach its target) will cause consecutive echo requests to be delayed, eventually resulting in timeouts. To avoid this, the PR makes a change to spawn a new thread for each call to `Process`.
This also adds a change that passes the `HttpContext.RequestAborted` cancellation token down the chain so that processing of echo requests could be cancelled if the http request is aborted.
**Ready**
=> Spawn new thread for processing echo requests

src/InformaticsGateway/Services/Http/DestinationAeTitleController.cs, src/InformaticsGateway/Services/Scu/ScuService.cs, src/InformaticsGateway/Services/Scu/ScuWorkRequest.cs, src/InformaticsGateway/Test/Services/Scu/ScuServiceTest.cs
Fixes # .
A few sentences describing the changes proposed in this pull request.
**Ready/Work in progress/Hold**
=> Spawn new thread for processing echo requests (#396)

docs/changelog.md, src/CLI/Logging/Log.cs, src/CLI/Monai.Deploy.InformaticsGateway.CLI.csproj, src/CLI/Options/Common.cs, src/CLI/Program.cs, src/CLI/Properties/launchSettings.json, src/CLI/Services/ConfigurationOptionAccessor.cs, src/CLI/Services/ConfigurationService.cs, src/CLI/Services/DockerRunner.cs, src/CLI/Services/EmbeddedResource.cs, src/CLI/Services/IConfigurationService.cs, src/CLI/Services/NLogConfigurationOptionAccessor.cs, src/CLI/Test/ConfigurationOptionAccessorTest.cs, src/CLI/Test/ConfigurationServiceTest.cs, src/CLI/Test/DockerRunnerTest.cs, src/CLI/Test/NLogConfigurationOptionAccessorTest.cs, src/CLI/Test/ProgramTest.cs
Fixes #435 to read application's log output directory path from NLog config file instead of `appsettings.json` since we've moved to NLog.
**Ready**
=> gh-435 Fix CLI to read log dir path from NLog config file

src/Api/DicomAssociationInfo.cs, src/Database/EntityFramework/Configuration/DicomAssociationInfoConfiguration.cs, src/Database/EntityFramework/Migrations/20230907182457_R4_0.4.1.Designer.cs, src/Database/EntityFramework/Migrations/20230907182457_R4_0.4.1.cs, src/Database/EntityFramework/Test/DicomAssociationInfoRepositoryTest.cs, src/Database/MongoDB/Integration.Test/DicomAssociationInfoRepositoryTest.cs, src/InformaticsGateway/Logging/Log.500.ExportService.cs, src/InformaticsGateway/Services/Connectors/PayloadMoveActionHandler.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationActionHandler.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs, src/InformaticsGateway/Services/Export/ExportRequestEventDetails.cs, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityHandler.cs, src/InformaticsGateway/Services/Scp/ApplicationEntityManager.cs, src/InformaticsGateway/Services/Scp/IApplicationEntityHandler.cs, src/InformaticsGateway/Services/Scp/IApplicationEntityManager.cs, src/InformaticsGateway/Services/Scp/ScpServiceInternal.cs, src/InformaticsGateway/Test/Monai.Deploy.InformaticsGateway.Test.csproj, src/InformaticsGateway/Test/Services/Common/InputDataPluginEngineFactoryTest.cs, src/InformaticsGateway/Test/Services/Common/OutputDataPluginEngineFactoryTest.cs
Add payload IDs to the `DicomAssociationInfo` table
**Ready*
=> Store payload IDs in DicomAssociationInfo table

.github/workflows/ci.yml, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Client/Test/packages.lock.json, src/Database/EntityFramework/Test/packages.lock.json, src/Database/EntityFramework/packages.lock.json, src/Database/packages.lock.json, src/InformaticsGateway/Services/Scp/ScpServiceInternal.cs, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/packages.lock.json
Fix to include `Monai.Deploy.InformaticsGateway.Common` in the `Monai.Deploy.InformaticsGateway.Api` Nuget package.
**Ready**
=> Include project references in the nuget package

docs/api/rest/dicom-association.md, src/Configuration/EndpointSettings.cs, src/Configuration/HttpEndpointSettings.cs, src/Configuration/InformaticsGatewayConfiguration.cs, src/Database/Api/Repositories/IDicomAssociationInfoRepository.cs, src/Database/EntityFramework/Repositories/DicomAssociationInfoRepository.cs, src/Database/EntityFramework/Test/DicomAssociationInfoRepositoryTest.cs, src/Database/MongoDB/Integration.Test/DicomAssociationInfoRepositoryTest.cs, src/Database/MongoDB/Repositories/DicomAssociationInfoRepository.cs, src/Database/MongoDB/Repositories/MongoDBRepositoryBase.cs, src/InformaticsGateway/Logging/Log.0.General.cs, src/InformaticsGateway/Logging/Log.8000.HttpServices.cs, src/InformaticsGateway/Program.cs, src/InformaticsGateway/Services/Common/Pagination/PagedResponse.cs, src/InformaticsGateway/Services/Common/Pagination/PaginationFilter.cs, src/InformaticsGateway/Services/Common/Pagination/Response.cs, src/InformaticsGateway/Services/Common/Pagination/TimeFilter.cs, src/InformaticsGateway/Services/Http/ApiControllerBase.cs, src/InformaticsGateway/Services/Http/DicomAssociationInfoController.cs, src/InformaticsGateway/Services/Http/PagedApiControllerBase.cs, src/InformaticsGateway/Services/UriService/IUriService.cs, src/InformaticsGateway/Services/UriService/UriService.cs, src/InformaticsGateway/Test/Services/Common/Pagination/PagedResponseTest.cs, src/InformaticsGateway/Test/Services/Http/DicomAssociationInfoControllerTest.cs
Implementation for the Dicom Association Controller
**Ready**
=> DicomAssociation Controller

Dockerfile, doc/dependency_decisions.yml, src/Api/packages.lock.json, src/CLI/packages.lock.json, src/Configuration/packages.lock.json, src/InformaticsGateway/Services/HealthLevel7/MllpService.cs, src/InformaticsGateway/Test/Services/HealthLevel7/MllpServiceTest.cs
Fixes # .
An issue where if the HL7Config had an empty string for the plugin name, it failed to process the Hl7Messages
**Ready**
=> fix for where hl7Config plugin is blank
