.github/.gitversion.yml, .github/workflows/release.yml, Dockerfile, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/CLI/Monai.Deploy.InformaticsGateway.CLI.csproj, src/Client.Common/Monai.Deploy.InformaticsGateway.Client.Common.csproj, src/Client/Monai.Deploy.InformaticsGateway.Client.csproj, src/Common/Monai.Deploy.InformaticsGateway.Common.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/Database/Monai.Deploy.InformaticsGateway.Database.csproj, src/DicomWebClient/Monai.Deploy.InformaticsGateway.DicomWeb.Client.csproj, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj
Fixes #42
Create a new Release pipeline that utilizes [gitversion](https://gitversion.net/) to determine the build number and then release the following:
- Docker image with Informatics Gateway
- CLI (Linux x64)
**Work in progress**
=> #42 Add release pipeline

.editorconfig, .github/workflows/ci.yml, CONTRIBUTING.md, README.md, codecov.yml, docs/changelog.md, docs/setup/setup.md
- Update user guide for 0.1.0 release
- Update changelog for release
**Work in progress**
=> Prepare for 0.1.0 release

.github/pull_request_template.md, .github/workflows/ci.yml, NuGetDefense.json
Add NuGetDefense Scanning
**Ready**
=> Add NuGetDefense Scanning

.dockerignore, .github/workflows/ci.yml, .vscode/launch.json, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/InformaticsGateway/Logging/Log.cs, src/InformaticsGateway/Program.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs, src/InformaticsGateway/Services/Export/ExportRequestDataMessage.cs, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs, src/InformaticsGateway/Test/Services/Export/DicomWebExportServiceTest.cs, src/InformaticsGateway/Test/Services/Export/ExportServiceBaseTest.cs, src/InformaticsGateway/Test/Services/Export/ScuExportServiceTest.cs, tests/Integration.Test/Features/AcrApi.feature, tests/Integration.Test/Features/AcrApi.feature.cs, tests/Integration.Test/Features/DicomDimseScp.feature, tests/Integration.Test/Features/DicomDimseScp.feature.cs, tests/Integration.Test/Features/DicomDimseScu.feature, tests/Integration.Test/Features/DicomDimseScu.feature.cs, tests/Integration.Test/Features/DicomWebExport.feature, tests/Integration.Test/Features/DicomWebExport.feature.cs, tests/Integration.Test/Hooks/RabbitMqHooks.cs, tests/Integration.Test/StepDefinitions/AcrApiStepDefinitions.cs, tests/Integration.Test/StepDefinitions/DicomDimseScpServicesStepDefinitions.cs, tests/Integration.Test/StepDefinitions/ExportServicesStepDefinitions.cs, tests/Integration.Test/configs/informatics-gateway.json
Remove storage & messaging code and replace with NuGet packages.
**Ready/Work in progress/Hold**
=> Delete messaging & storage code and use NuGet packages

.github/workflows/ci.yml, tests/Integration.Test/Drivers/Configurations.cs, tests/Integration.Test/Drivers/DicomInstanceGenerator.cs, tests/Integration.Test/Features/DicomDimseScp.feature, tests/Integration.Test/Features/DicomDimseScp.feature.cs, tests/Integration.Test/README.md, tests/Integration.Test/run.sh
Split integration test, by feature, into multiple jobs
**Ready**
=> gh-28 Split integration test to multiple jobs

tests/Integration.Test/study.json
Adjust study specs to generate more realistic dataset for integration tests.
**Ready/Work in progress/Hold**
=> Adjust study specs for integration test

guidelines/mig-drd.md
Updates the requirements for REQ-DCW-06 DICOMWeb STOW-RS.
**Ready**
=> Update REQ-DCW-06 DICOMWeb STOW-RS

src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/InformaticsGateway/Program.cs, src/InformaticsGateway/Services/Connectors/PayloadNotificationService.cs, src/InformaticsGateway/Services/Export/DicomWebExportService.cs, src/InformaticsGateway/Services/Export/ExportRequestDataMessage.cs, src/InformaticsGateway/Services/Export/ExportRequestEventDetails.cs, src/InformaticsGateway/Services/Export/ExportServiceBase.cs, src/InformaticsGateway/Services/Export/ScuExportService.cs, src/InformaticsGateway/Test/DummyMessagingService.cs, src/InformaticsGateway/Test/DummyStorageService.cs, src/InformaticsGateway/Test/Services/Connectors/PayloadNotificationServiceTest.cs, src/InformaticsGateway/Test/Services/Export/DicomWebExportServiceTest.cs, src/InformaticsGateway/Test/Services/Export/ExportServiceBaseTest.cs, src/InformaticsGateway/Test/Services/Export/ScuExportServiceTest.cs, src/InformaticsGateway/Test/appsettings.json, src/InformaticsGateway/appsettings.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj, tests/Integration.Test/StepDefinitions/ExportServicesStepDefinitions.cs, tests/Integration.Test/configs/informatics-gateway.json
Loads messaging plug-in dynamically
**Ready**
=> Dynamically load messaging plug-in

.github/workflows/ci.yml, NuGetDefense.json
Fix nugetdefnse failure due to API call rate limit
**Ready**
=> Use OSS Index API to avoid API rate limit

src/InformaticsGateway/nlog.config
Signed-off-by: Neil South <neil.south@answerdigital.com>
=> reduced logstash logging

doc/dependency_decisions.yml, docs/compliance/third-party-licenses.md, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Api/Test/packages.lock.json, src/Api/packages.lock.json, src/CLI/Monai.Deploy.InformaticsGateway.CLI.csproj, src/CLI/Test/packages.lock.json, src/CLI/packages.lock.json, src/Client/Test/packages.lock.json, src/Client/packages.lock.json, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/Configuration/Test/packages.lock.json, src/Configuration/packages.lock.json, src/Database/Api/Test/packages.lock.json, src/Database/Api/packages.lock.json, src/Database/EntityFramework/Test/packages.lock.json, src/Database/EntityFramework/packages.lock.json, src/Database/Monai.Deploy.InformaticsGateway.Database.csproj, src/Database/MongoDB/Integration.Test/Monai.Deploy.InformaticsGateway.Database.MongoDB.Integration.Test.csproj, src/Database/MongoDB/Integration.Test/packages.lock.json, src/Database/MongoDB/packages.lock.json, src/Database/packages.lock.json, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj, tests/Integration.Test/packages.lock.json
Updates messaging library to 0.1.20 to handle exception of unavailable previously created dead-letter queues.
**Ready**
=> Update messaging lib to 0.1.20

src/InformaticsGateway/Logging/Log.700.PayloadService.cs, src/InformaticsGateway/Services/Connectors/PayloadMoveActionHandler.cs
Logs payload move exception before listing all files.
**Ready**
=> Log payload move exception explicitly

doc/dependency_decisions.yml, docs/compliance/third-party-licenses.md, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Api/Test/packages.lock.json, src/Api/packages.lock.json, src/CLI/Test/packages.lock.json, src/CLI/packages.lock.json, src/Client/Test/packages.lock.json, src/Client/packages.lock.json, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/Configuration/Test/packages.lock.json, src/Configuration/packages.lock.json, src/Database/Api/Test/packages.lock.json, src/Database/Api/packages.lock.json, src/Database/EntityFramework/Test/packages.lock.json, src/Database/EntityFramework/packages.lock.json, src/Database/MongoDB/Integration.Test/packages.lock.json, src/Database/MongoDB/packages.lock.json, src/Database/packages.lock.json, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj, tests/Integration.Test/packages.lock.json
Update message lib to 0.1.21
**Ready**
=> Update message lib to 0.1.21

doc/dependency_decisions.yml, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Api/Test/packages.lock.json, src/Api/packages.lock.json, src/CLI/Test/packages.lock.json, src/CLI/packages.lock.json, src/Client.Common/Test/packages.lock.json, src/Client/Test/packages.lock.json, src/Client/packages.lock.json, src/Common/Test/packages.lock.json, src/Configuration/Monai.Deploy.InformaticsGateway.Configuration.csproj, src/Configuration/Test/packages.lock.json, src/Configuration/packages.lock.json, src/Database/Api/Test/packages.lock.json, src/Database/Api/packages.lock.json, src/Database/EntityFramework/Test/packages.lock.json, src/Database/EntityFramework/packages.lock.json, src/Database/MongoDB/Integration.Test/packages.lock.json, src/Database/MongoDB/packages.lock.json, src/Database/packages.lock.json, src/DicomWebClient/Test/packages.lock.json, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj, tests/Integration.Test/packages.lock.json
Fixes # .
upping packages
**Ready**
=> upping licenses

doc/dependency_decisions.yml, src/Api/Monai.Deploy.InformaticsGateway.Api.csproj, src/Api/Test/packages.lock.json, src/Api/packages.lock.json, src/CLI/Test/packages.lock.json, src/CLI/packages.lock.json, src/Client/Test/packages.lock.json, src/Client/packages.lock.json, src/Configuration/Test/packages.lock.json, src/Configuration/packages.lock.json, src/Database/Api/Monai.Deploy.InformaticsGateway.Database.Api.csproj, src/Database/Api/Test/packages.lock.json, src/Database/Api/packages.lock.json, src/Database/EntityFramework/Monai.Deploy.InformaticsGateway.Database.EntityFramework.csproj, src/Database/EntityFramework/Test/Monai.Deploy.InformaticsGateway.Database.EntityFramework.Test.csproj, src/Database/EntityFramework/Test/packages.lock.json, src/Database/EntityFramework/packages.lock.json, src/Database/Monai.Deploy.InformaticsGateway.Database.csproj, src/Database/MongoDB/Integration.Test/packages.lock.json, src/Database/MongoDB/packages.lock.json, src/Database/packages.lock.json, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Test/Monai.Deploy.InformaticsGateway.Test.csproj, src/InformaticsGateway/Test/packages.lock.json, src/InformaticsGateway/packages.lock.json, tests/Integration.Test/Monai.Deploy.InformaticsGateway.Integration.Test.csproj, tests/Integration.Test/packages.lock.json
Merge develop into release 0.3.14
=> Update Storage & Messaging libraries (#355)

.github/.gitversion.yml, docs/changelog.md, src/Client/Test/Monai.Deploy.InformaticsGateway.Client.Test.csproj, src/Database/Monai.Deploy.InformaticsGateway.Database.csproj
Merged from main and flattened commits to removed un-signed commits.
**Ready**
=> Merged from main

docs/api/rest/config.md, src/Common/packages.lock.json, src/Database/Api/Repositories/ISourceApplicationEntityRepository.cs, src/Database/EntityFramework/Repositories/SourceApplicationEntityRepository.cs, src/Database/EntityFramework/Test/SourceApplicationEntityRepositoryTest.cs, src/Database/MongoDB/Integration.Test/SourceApplicationEntityRepositoryTest.cs, src/Database/MongoDB/Repositories/SourceApplicationEntityRepository.cs, src/DicomWebClient/packages.lock.json, src/InformaticsGateway/Services/Http/SourceAeTitleController.cs, src/InformaticsGateway/Test/Services/Http/SourceAeTitleControllerTest.cs, src/InformaticsGateway/appsettings.Development.json
added the ability to get registered AETitle[] sources via an given AETitle
#390 
**Ready**
=> adding endpoint to get AETitles by AeTitle

src/Client/Test/packages.lock.json, src/InformaticsGateway/Monai.Deploy.InformaticsGateway.csproj, src/InformaticsGateway/Services/Http/SourceAeTitleController.cs, src/InformaticsGateway/Test/packages.lock.json, tests/Integration.Test/packages.lock.json
Fix get sources by AETitle endpoint
**Ready**
=> update get source by aetitle endpoint

docker-compose/docker-compose.yml, src/InformaticsGateway/Services/Http/Startup.cs
adds basic auth to swaggr for testing
**Ready**
=> adding basic auth to swagger

src/Api/Hl7ApplicationConfigEntity.cs, src/Api/Test/BaseApplicationEntityTest.cs, src/Api/Test/DestinationApplicationEntityTest.cs, src/Api/Test/Hl7ApplicationConfigEntityTest.cs, src/Api/Test/Monai.Deploy.InformaticsGateway.Api.Test.csproj, src/Api/Test/MonaiApplicationEntityTest.cs, src/Database/Api/Repositories/IHl7ApplicationConfigRepository.cs, src/Database/DatabaseManager.cs, src/Database/EntityFramework/Configuration/Hl7ApplicationConfigConfiguration.cs, src/Database/EntityFramework/InformaticsGatewayContext.cs, src/Database/EntityFramework/Repositories/Hl7ApplicationConfigRepository.cs, src/Database/MongoDB/Repositories/Hl7ApplicationConfigRepository.cs, src/InformaticsGateway/Logging/Log.8000.HttpServices.cs, src/InformaticsGateway/Services/DicomWeb/ContentTypes.cs, src/InformaticsGateway/Services/Http/Hl7ApplicationConfigController.cs, src/InformaticsGateway/Test/Monai.Deploy.InformaticsGateway.Test.csproj, src/InformaticsGateway/Test/Services/Http/Hl7ApplicationConfigControllerTest.cs, src/InformaticsGateway/Test/packages.lock.json
Changes for adding HL7 Application configuration endpoint.
**Work in progress**
=> Ai 292 hl 7 configuration
